Repository mongodb/mongodb-kubernetes-operator, pull requests merged in 2021-06, with the labels that each got.

#518 add detailed upgrade steps
  docs/install-upgrade.md
Labels: CLA - Verified, CLOUDP-91128

#561 Fixing the small issue with *
  docs/install-upgrade.md
Labels: CLOUDP-91939

#562 Fixing the Enterprise MongoDB Kubernetes
  docs/contributing.md
Labels: CLOUDP-91938

#580 Cloudp 78267 add arbiters to replicasets
  .github/workflows/e2e.yml
  api/v1/mongodbcommunity_types.go
  config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
  controllers/replica_set_controller.go
  controllers/validation/validation.go
  docs/RELEASE_NOTES.md
  pkg/automationconfig/automation_config.go
  pkg/automationconfig/automation_config_builder.go
  pkg/automationconfig/automation_config_test.go
  test/e2e/e2eutil.go
  test/e2e/mongodbtests/mongodbtests.go
  test/e2e/replica_set_arbiter/replica_set_arbiter_test.go
  test/e2e/util/wait/wait.go
Labels: CLOUDP-92626
