Repository mongodb/mongodb-kubernetes-operator, pull requests merged in 2022-01, with the labels that each got.

#848 Make mongod port configurable
  api/v1/mongodbcommunity_types.go
  api/v1/mongodbcommunity_types_test.go
  controllers/construct/build_statefulset_test.go
  controllers/construct/mongodbstatefulset.go
  controllers/replica_set_controller.go
  controllers/replicaset_controller_test.go
  controllers/testdata/specify_net_port.yaml
  pkg/automationconfig/automation_config.go
  pkg/automationconfig/automation_config_builder.go
  pkg/util/merge/merge_automationconfigs_test.go
  test/e2e/mongodbtests/mongodbtests.go
  test/e2e/replica_set_mongod_config/replica_set_mongod_config_test.go
Labels: CLOUDP-108983

#835 Cluster-wide deployment: Fix kustomize compatibility
  deploy/clusterwide/role_binding.yaml
Labels: safe-to-test, CLOUDP-108536

#836 Compatibility with Restricted PodSecurityPolicy (Operator Only)
  config/manager/manager.yaml
Labels: safe-to-test, CLOUDP-108535

#793 fix names from role to cluster_role and from role_binding to cluster_…
  deploy/clusterwide/cluster_role.yaml
  deploy/clusterwide/cluster_role_binding.yaml
Labels: safe-to-test, CLOUDP-107026

#842 Update mongodb.com_v1_hostpath.yaml
  config/samples/arbitrary_statefulset_configuration/mongodb.com_v1_hostpath.yaml
Labels: CLOUDP-108978
