Repository mongodb/mongodb-kubernetes-operator, pull requests merged in 2022-08, with the labels that each got.

#1042 CLOUDP-127633 Use read-only filesystem
  PROJECT
  controllers/construct/build_statefulset_test.go
  controllers/construct/mongodbstatefulset.go
  controllers/mongodb_tls_test.go
  docs/RELEASE_NOTES.md
  main.go
  pkg/kube/container/container_test.go
  pkg/kube/container/containers.go
  pkg/kube/podtemplatespec/podspec_template.go
  pkg/kube/podtemplatespec/podspec_template_test.go
Labels: safe-to-test

#1077 Fixed operator's version in manager.yaml
  config/manager/manager.yaml
Labels: CLOUDP-132981

#1068 Updated how-to-release.md
  docs/how-to-release.md
Labels: CLOUDP-132982

#1095 CLOUDP-127632 AllowPrivilegeEscalation set to false
  docs/RELEASE_NOTES.md
  pkg/kube/container/containers.go
Labels: safe-to-test

#1097 CLOUDP-133524 Upgrade Agent to the latest version
  release.json
Labels: safe-to-test
