Repository mongodb/mongodb-kubernetes-operator, pull requests merged in 2023-01, with the labels that each got.

#1179 test: use `T.Setenv` to set env vars in tests
  cmd/readiness/readiness_test.go
  controllers/construct/build_statefulset_test.go
  controllers/replicaset_controller_test.go
  pkg/util/envvar/envvars_test.go
Labels: safe-to-test

#1180 chore: improve code readability
  pkg/automationconfig/automation_config_builder.go
Labels: safe-to-test, CLOUDP-152478

#1199 Sync the Kind setup with the downstream
  scripts/dev/setup_kind_cluster.sh
Labels: safe-to-test, CLOUDP-154642
